version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students_db
    ports:
      - "5432:5432"
